name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install deps
        run: pnpm install
      - name: Lint source code
        run: pnpm lint
